export const WORKFLOW_FILTER_API = '/workflow/process/filter?limit=50&offset=0'
export const ORDER_WORKFLOW_ATTACH_API = '/workflow/process/start'
export const WORKFLOW_INSTANCE_BY_ENTITY_API = '/workflow/process/instance/get-entity'
export const WORKFLOW_PROCESS_FIND_API = '/workflow/process/find-id'
export const WORKFLOW_PREVIEW_API = '/workflow/process/preview'
export const ORDER_LOTS_FIND_API = '/qms/warehouse-paracel/find-entity'
export const ORDER_WORKFLOW_ENTITY_TYPE = 'order'
export const LOT_WORKFLOW_ENTITY_TYPE = 'WAREHOUSE_PARCEL'
