import { EXTENDED_LANDING_BLOCKS } from './extendedBlockRegistry'
import { CUSTOM_JSX_TEMPLATE, CUSTOM_JSX_TYPE } from './customJsx'

export const COMMON_BLOCK_DEFAULTS = {
  anchorId: '',
  sectionBackground: '',
  sectionBackgroundImage: '',
  sectionBackgroundPattern: 'none',
  sectionTextColor: '',
  sectionMaxWidth: '0',
  sectionPaddingDesktop: '0',
  sectionPaddingMobile: '0',
  hideOnDesktop: false,
  hideOnMobile: false,
  entranceAnimation: 'none',
  boxMarginTop: '0',
  boxMarginRight: '0',
  boxMarginBottom: '0',
  boxMarginLeft: '0',
  boxPaddingTop: '0',
  boxPaddingRight: '0',
  boxPaddingBottom: '0',
  boxPaddingLeft: '0',
  boxBackground: '',
  boxBorderWidth: '0',
  boxBorderStyle: 'solid',
  boxBorderColor: '#e8e8ee',
  boxBorderRadius: '0',
  boxShadow: 'none',
}

export const NESTED_BLOCK_BOX_FIELDS = [
  { name: 'boxMarginTop', label: 'Margin trên (px)', control: 'number' },
  { name: 'boxMarginRight', label: 'Margin phải (px)', control: 'number' },
  { name: 'boxMarginBottom', label: 'Margin dưới (px)', control: 'number' },
  { name: 'boxMarginLeft', label: 'Margin trái (px)', control: 'number' },
  { name: 'boxPaddingTop', label: 'Padding trên (px)', control: 'number' },
  { name: 'boxPaddingRight', label: 'Padding phải (px)', control: 'number' },
  { name: 'boxPaddingBottom', label: 'Padding dưới (px)', control: 'number' },
  { name: 'boxPaddingLeft', label: 'Padding trái (px)', control: 'number' },
  { name: 'boxBackground', label: 'Màu nền block', control: 'colorOptional' },
  { name: 'boxBorderWidth', label: 'Độ dày border (px)', control: 'number' },
  {
    name: 'boxBorderStyle', label: 'Kiểu border', control: 'select', options: [
      { label: 'Liền', value: 'solid' },
      { label: 'Nét đứt', value: 'dashed' },
      { label: 'Chấm', value: 'dotted' },
      { label: 'Hai đường', value: 'double' },
    ],
  },
  { name: 'boxBorderColor', label: 'Màu border', control: 'color' },
  { name: 'boxBorderRadius', label: 'Bo góc (px)', control: 'number' },
  {
    name: 'boxShadow', label: 'Đổ bóng', control: 'select', options: [
      { label: 'Không dùng', value: 'none' },
      { label: 'Nhẹ', value: 'soft' },
      { label: 'Vừa', value: 'medium' },
      { label: 'Đậm', value: 'strong' },
    ],
  },
]

export const COMMON_BLOCK_FIELDS = [
  { name: 'anchorId', label: 'Anchor ID dùng cho menu', control: 'text' },
  { name: 'sectionBackground', label: 'Màu nền khu vực', control: 'colorOptional' },
  { name: 'sectionBackgroundImage', label: 'Ảnh nền khu vực', control: 'image', uploadFolder: 'landing/section' },
  {
    name: 'sectionBackgroundPattern', label: 'Họa tiết nền', control: 'select', options: [
      { label: 'Không dùng', value: 'none' },
      { label: 'Dệt chéo', value: 'woven' },
      { label: 'Lưới', value: 'grid' },
      { label: 'Chấm', value: 'dots' },
    ],
  },
  { name: 'sectionTextColor', label: 'Màu chữ khu vực', control: 'colorOptional' },
  { name: 'sectionMaxWidth', label: 'Độ rộng tối đa (0 = toàn chiều rộng)', control: 'number' },
  { name: 'sectionPaddingDesktop', label: 'Khoảng đệm desktop (px)', control: 'number' },
  { name: 'sectionPaddingMobile', label: 'Khoảng đệm mobile (px)', control: 'number' },
  { name: 'hideOnDesktop', label: 'Ẩn trên desktop', control: 'checkbox' },
  { name: 'hideOnMobile', label: 'Ẩn trên mobile', control: 'checkbox' },
  {
    name: 'entranceAnimation', label: 'Hiệu ứng xuất hiện', control: 'select', options: [
      { label: 'Không dùng', value: 'none' },
      { label: 'Mờ dần', value: 'fade' },
      { label: 'Trượt lên', value: 'fade-up' },
      { label: 'Thu phóng nhẹ', value: 'zoom' },
    ],
  },
]

const createId = (type) => {
  const suffix = (typeof window !== 'undefined' && window.crypto?.randomUUID?.())
    ?? `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
  return `${type}-${suffix}`
}

export const LANDING_BLOCKS = [
  {
    type: 'breadcrumb',
    label: 'Breadcrumb',
    icon: '›',
    defaults: {
      items: [{ id: 'c1', text: 'Trang chủ', url: '/' }],
      separator: '/',
      align: 'left',
      background: 'transparent',
      textColor: '#1677ff',
    },
    fields: [
      {
        name: 'items',
        label: 'Các cấp điều hướng',
        control: 'repeater',
        itemFields: [
          { name: 'text', label: 'Văn bản', control: 'text' },
          { name: 'url', label: 'Đường dẫn', control: 'text' },
        ],
        itemDefaults: { id: '', text: 'Cấp mới', url: '/' },
      },
      { name: 'separator', label: 'Ký tự phân cách', control: 'text' },
      {
        name: 'align', label: 'Căn chỉnh', control: 'select', options: [
          { label: 'Trái', value: 'left' },
          { label: 'Giữa', value: 'center' },
          { label: 'Phải', value: 'right' },
        ],
      },
      { name: 'background', label: 'Màu nền', control: 'colorOptional' },
      { name: 'textColor', label: 'Màu chữ', control: 'color' },
    ],
  },
  {
    type: 'navbar',
    label: 'Thanh điều hướng',
    icon: '☰',
    defaults: {
      brandName: 'Tên thương hiệu',
      logoUrl: '',
      logoAlt: 'Logo thương hiệu',
      brandUrl: '/',
      brandOpenInNewTab: false,
      sticky: false,
      backgroundColor: '#ffffff',
      textColor: '#16161a',
      links: [
        { label: 'Trang chủ', url: '#' },
        { label: 'Giới thiệu', url: '#gioi-thieu' },
      ],
      buttonText: 'Liên hệ',
      actions: [
        {
          label: 'Liên hệ',
          url: '/contact',
          openInNewTab: false,
        },
      ],
    },
    fields: [
      { name: 'brandName', label: 'Tên thương hiệu', control: 'text' },
      { name: 'logoUrl', label: 'Logo', control: 'image', uploadFolder: 'landing/logo' },
      { name: 'logoAlt', label: 'Mô tả logo', control: 'text' },
      { name: 'brandUrl', label: 'Liên kết logo / thương hiệu', control: 'text' },
      { name: 'brandOpenInNewTab', label: 'Mở liên kết logo trong tab mới', control: 'checkbox' },
      { name: 'sticky', label: 'Cố định khi cuộn trang', control: 'checkbox' },
      { name: 'backgroundColor', label: 'Màu nền', control: 'color' },
      { name: 'textColor', label: 'Màu chữ', control: 'color' },
      {
        name: 'links',
        label: 'Liên kết menu',
        control: 'repeater',
        itemFields: [
          { name: 'label', label: 'Nhãn', control: 'text' },
          { name: 'url', label: 'Liên kết', control: 'text' },
        ],
        itemDefaults: { label: 'Liên kết mới', url: '#' },
      },
      {
        name: 'actions',
        label: 'Nút hành động',
        control: 'repeater',
        itemFields: [
          { name: 'label', label: 'Nhãn nút', control: 'text' },
          { name: 'url', label: 'Đi tới trang/URL', control: 'text' },
          { name: 'openInNewTab', label: 'Mở trong tab mới', control: 'checkbox' },
        ],
        itemDefaults: {
          label: 'Nút mới',
          url: '/',
          openInNewTab: false,
        },
      },
    ],
  },
  {
    type: 'hero',
    label: 'Hero',
    icon: '▣',
    defaults: {
      eyebrow: 'GIỚI THIỆU',
      title: 'Tiêu đề nổi bật của trang',
      description: 'Mô tả ngắn giúp khách hàng hiểu giá trị bạn mang lại.',
      primaryButtonText: 'Bắt đầu',
      primaryButtonUrl: '/get-started',
      primaryButtonOpenInNewTab: false,
      secondaryButtonText: 'Tìm hiểu thêm',
      secondaryButtonUrl: '#features',
      secondaryButtonOpenInNewTab: false,
      background: '#fafaff',
      backgroundType: 'color',
      backgroundImageUrl: '',
      backgroundVideoUrl: '',
      overlayColor: '#000000',
      overlayOpacity: '35',
      layout: 'center',
      minHeight: '520',
      mobileMinHeight: '420',
      textColor: '#16161a',
      titleFontSize: '48',
      mobileTitleFontSize: '36',
      descriptionFontSize: '18',
      mobileDescriptionFontSize: '16',
      splitLayout: false,
      visualPosition: 'right',
      visualBlocks: [],
    },
    fields: [
      { name: 'eyebrow', label: 'Nhãn phía trên', control: 'text' },
      { name: 'title', label: 'Tiêu đề', control: 'textarea' },
      { name: 'description', label: 'Mô tả', control: 'textarea' },
      { name: 'primaryButtonText', label: 'Nút chính', control: 'text' },
      { name: 'primaryButtonUrl', label: 'URL nút chính', control: 'text' },
      { name: 'primaryButtonOpenInNewTab', label: 'Mở nút chính trong tab mới', control: 'checkbox' },
      { name: 'secondaryButtonText', label: 'Nút phụ', control: 'text' },
      { name: 'secondaryButtonUrl', label: 'URL nút phụ', control: 'text' },
      { name: 'secondaryButtonOpenInNewTab', label: 'Mở nút phụ trong tab mới', control: 'checkbox' },
      { name: 'background', label: 'Màu nền', control: 'color' },
      {
        name: 'backgroundType',
        label: 'Loại nền',
        control: 'select',
        options: [
          { label: 'Màu nền', value: 'color' },
          { label: 'Ảnh nền', value: 'image' },
          { label: 'Video nền', value: 'video' },
        ],
      },
      { name: 'backgroundImageUrl', label: 'Ảnh nền', control: 'image', uploadFolder: 'landing/hero' },
      { name: 'backgroundVideoUrl', label: 'URL video nền', control: 'text' },
      { name: 'overlayColor', label: 'Màu lớp phủ', control: 'color' },
      { name: 'overlayOpacity', label: 'Độ mờ lớp phủ (%)', control: 'number' },
      {
        name: 'layout',
        label: 'Vị trí nội dung',
        control: 'select',
        options: [
          { label: 'Bên trái', value: 'left' },
          { label: 'Ở giữa', value: 'center' },
          { label: 'Bên phải', value: 'right' },
        ],
      },
      { name: 'minHeight', label: 'Chiều cao desktop (px)', control: 'number' },
      { name: 'mobileMinHeight', label: 'Chiều cao mobile (px)', control: 'number' },
      { name: 'textColor', label: 'Màu chữ', control: 'color' },
      { name: 'titleFontSize', label: 'Cỡ tiêu đề desktop (px)', control: 'number' },
      { name: 'mobileTitleFontSize', label: 'Cỡ tiêu đề mobile (px)', control: 'number' },
      { name: 'descriptionFontSize', label: 'Cỡ mô tả desktop (px)', control: 'number' },
      { name: 'mobileDescriptionFontSize', label: 'Cỡ mô tả mobile (px)', control: 'number' },
      { name: 'splitLayout', label: 'Bố cục nội dung và hình minh họa hai cột', control: 'checkbox' },
      {
        name: 'visualPosition', label: 'Vị trí vùng minh họa', control: 'select', options: [
          { label: 'Bên phải', value: 'right' },
          { label: 'Bên trái', value: 'left' },
        ],
      },
      { name: 'visualBlocks', label: 'Block trong vùng minh họa', control: 'nestedBlocks' },
    ],
  },
  {
    type: 'bannerSlider',
    label: 'Banner slide',
    icon: '▤',
    defaults: {
      displayMode: 'image',
      images: [],
      announcements: [
        { text: 'BST mới vừa ra mắt', url: '#' },
        { text: 'Miễn phí giao mẫu trong nội thành', url: '#' },
        { text: 'Đặt sỉ từ 30m, không giới hạn màu', url: '#' },
      ],
      tickerSpeed: '28',
      tickerDirection: 'rtl',
      tickerBackground: '#232D4B',
      tickerTextColor: '#FAF7EF',
      tickerAccentColor: '#D9A441',
      tickerSeparator: '◆',
      autoplay: true,
      pauseOnHover: true,
      interval: '5',
      height: '420',
      mobileHeight: '280',
      showDots: true,
    },
    fields: [
      {
        name: 'displayMode', label: 'Kiểu banner', control: 'select', options: [
          { label: 'Banner ảnh', value: 'image' },
          { label: 'Dòng chữ chạy', value: 'ticker' },
        ],
      },
      {
        name: 'announcements', label: 'Nội dung dòng chữ chạy', control: 'repeater',
        itemFields: [
          { name: 'text', label: 'Nội dung', control: 'text' },
          { name: 'url', label: 'Liên kết', control: 'text' },
        ],
        itemDefaults: { text: 'Thông báo mới', url: '#' },
      },
      { name: 'tickerSpeed', label: 'Thời gian chạy hết một vòng (giây)', control: 'number' },
      {
        name: 'tickerDirection', label: 'Hướng chạy', control: 'select', options: [
          { label: 'Phải sang trái', value: 'rtl' },
          { label: 'Trái sang phải', value: 'ltr' },
        ],
      },
      { name: 'tickerBackground', label: 'Màu nền dòng chữ', control: 'color' },
      { name: 'tickerTextColor', label: 'Màu chữ', control: 'color' },
      { name: 'tickerAccentColor', label: 'Màu dấu phân cách', control: 'color' },
      { name: 'tickerSeparator', label: 'Dấu phân cách', control: 'text' },
      {
        name: 'images',
        label: 'Ảnh banner',
        control: 'multiImage',
        uploadFolder: 'landing/banner',
      },
      { name: 'autoplay', label: 'Tự động chuyển slide', control: 'checkbox' },
      { name: 'pauseOnHover', label: 'Tạm dừng khi rê chuột', control: 'checkbox' },
      { name: 'interval', label: 'Thời gian chuyển (giây)', control: 'number' },
      { name: 'height', label: 'Chiều cao desktop (px)', control: 'number' },
      { name: 'mobileHeight', label: 'Chiều cao mobile (px)', control: 'number' },
      { name: 'showDots', label: 'Hiển thị chấm điều hướng', control: 'checkbox' },
    ],
  },
  {
    type: 'heading',
    label: 'Tiêu đề',
    icon: 'H',
    defaults: {
      text: 'Tiêu đề mới',
      level: 'h2',
      align: 'left',
      fontSize: '36',
      mobileFontSize: '28',
      fontWeight: '700',
      color: '#16161a',
      maxWidth: '1120',
      marginTop: '0',
      marginBottom: '0',
    },
    fields: [
      { name: 'text', label: 'Nội dung', control: 'textarea' },
      {
        name: 'level',
        label: 'Cấp tiêu đề',
        control: 'select',
        options: [
          { label: 'H1', value: 'h1' },
          { label: 'H2', value: 'h2' },
          { label: 'H3', value: 'h3' },
        ],
      },
      {
        name: 'align',
        label: 'Căn lề',
        control: 'select',
        options: [
          { label: 'Trái', value: 'left' },
          { label: 'Giữa', value: 'center' },
          { label: 'Phải', value: 'right' },
        ],
      },
      { name: 'fontSize', label: 'Cỡ chữ desktop (px)', control: 'number' },
      { name: 'mobileFontSize', label: 'Cỡ chữ mobile (px)', control: 'number' },
      {
        name: 'fontWeight', label: 'Độ đậm', control: 'select', options: [
          { label: 'Thường', value: '400' }, { label: 'Vừa', value: '500' },
          { label: 'Đậm vừa', value: '600' }, { label: 'Đậm', value: '700' },
          { label: 'Rất đậm', value: '800' },
        ],
      },
      { name: 'color', label: 'Màu chữ', control: 'color' },
      { name: 'maxWidth', label: 'Độ rộng tối đa (px)', control: 'number' },
      { name: 'marginTop', label: 'Lề trên (px)', control: 'number' },
      { name: 'marginBottom', label: 'Lề dưới (px)', control: 'number' },
    ],
  },
  {
    type: 'text',
    label: 'Văn bản',
    icon: '¶',
    defaults: {
      text: '<p>Nhập nội dung văn bản tại đây.</p>',
      align: 'left',
    },
    fields: [
      { name: 'text', label: 'Nội dung có định dạng', control: 'richtext' },
      {
        name: 'align',
        label: 'Căn lề',
        control: 'select',
        options: [
          { label: 'Trái', value: 'left' },
          { label: 'Giữa', value: 'center' },
          { label: 'Phải', value: 'right' },
        ],
      },
    ],
  },
  {
    type: 'image',
    label: 'Hình ảnh',
    icon: '▧',
    defaults: {
      src: 'https://placehold.co/1200x520/f4f2ff/6550d8?text=Hinh+anh',
      alt: 'Hình ảnh',
      caption: '',
      captionBackground: 'transparent',
      captionColor: '#8a8a96',
      radius: '12',
      width: '100',
      mobileWidth: '100',
      aspectRatio: 'auto',
      objectFit: 'cover',
      fillContainer: false,
      focalX: '50',
      focalY: '50',
      link: '',
      openInNewTab: false,
      lazyLoad: true,
    },
    fields: [
      { name: 'src', label: 'Hình ảnh', control: 'image', uploadFolder: 'landing/image' },
      { name: 'alt', label: 'Văn bản thay thế', control: 'text' },
      { name: 'caption', label: 'Chú thích', control: 'text' },
      { name: 'captionBackground', label: 'Màu nền chú thích', control: 'colorOptional' },
      { name: 'captionColor', label: 'Màu chữ chú thích', control: 'color' },
      { name: 'radius', label: 'Bo góc (px)', control: 'number' },
      { name: 'width', label: 'Độ rộng desktop (%)', control: 'number' },
      { name: 'mobileWidth', label: 'Độ rộng mobile (%)', control: 'number' },
      {
        name: 'aspectRatio', label: 'Tỷ lệ ảnh', control: 'select', options: [
          { label: 'Tự nhiên', value: 'auto' }, { label: '16:9', value: '16/9' },
          { label: '4:3', value: '4/3' }, { label: '1:1', value: '1/1' },
          { label: '3:4', value: '3/4' },
        ],
      },
      {
        name: 'objectFit', label: 'Cách hiển thị', control: 'select', options: [
          { label: 'Cắt phủ đầy', value: 'cover' }, { label: 'Hiển thị toàn ảnh', value: 'contain' },
          { label: 'Kéo đầy khung', value: 'fill' },
        ],
      },
      { name: 'fillContainer', label: 'Phủ kín vùng chứa / cột', control: 'checkbox' },
      { name: 'focalX', label: 'Điểm lấy nét ngang (%)', control: 'number' },
      { name: 'focalY', label: 'Điểm lấy nét dọc (%)', control: 'number' },
      { name: 'link', label: 'Liên kết khi click', control: 'text' },
      { name: 'openInNewTab', label: 'Mở trong tab mới', control: 'checkbox' },
      { name: 'lazyLoad', label: 'Tải ảnh trì hoãn', control: 'checkbox' },
    ],
  },
  {
    type: 'button',
    label: 'Nút bấm',
    icon: '▰',
    defaults: {
      text: 'Xem thêm',
      url: '#',
      align: 'left',
      openInNewTab: false,
      style: 'primary',
      color: '#7c5cff',
      textColor: '#ffffff',
      size: 'medium',
      fullWidthMobile: false,
      icon: 'none',
      iconPosition: 'left',
      disabled: false,
    },
    fields: [
      { name: 'text', label: 'Nhãn nút', control: 'text' },
      { name: 'url', label: 'Liên kết', control: 'text' },
      { name: 'openInNewTab', label: 'Mở trong tab mới', control: 'checkbox' },
      {
        name: 'style', label: 'Kiểu nút', control: 'select', options: [
          { label: 'Primary', value: 'primary' }, { label: 'Secondary', value: 'secondary' },
          { label: 'Link', value: 'link' },
        ],
      },
      { name: 'color', label: 'Màu nút', control: 'color' },
      { name: 'textColor', label: 'Màu chữ', control: 'color' },
      {
        name: 'size', label: 'Kích thước', control: 'select', options: [
          { label: 'Nhỏ', value: 'small' }, { label: 'Vừa', value: 'medium' },
          { label: 'Lớn', value: 'large' },
        ],
      },
      { name: 'fullWidthMobile', label: 'Full-width trên mobile', control: 'checkbox' },
      {
        name: 'icon', label: 'Icon', control: 'select', options: [
          { label: 'Không dùng', value: 'none' }, { label: 'Mũi tên', value: 'arrow' },
          { label: 'Tải xuống', value: 'download' }, { label: 'Điện thoại', value: 'phone' },
          { label: 'Email', value: 'email' },
        ],
      },
      {
        name: 'iconPosition', label: 'Vị trí icon', control: 'select', options: [
          { label: 'Bên trái', value: 'left' }, { label: 'Bên phải', value: 'right' },
        ],
      },
      { name: 'disabled', label: 'Vô hiệu hóa nút', control: 'checkbox' },
      {
        name: 'align',
        label: 'Căn lề',
        control: 'select',
        options: [
          { label: 'Trái', value: 'left' },
          { label: 'Giữa', value: 'center' },
          { label: 'Phải', value: 'right' },
        ],
      },
    ],
  },
  {
    type: 'features',
    label: 'Danh sách tính năng',
    icon: '▦',
    defaults: {
      desktopColumns: '3',
      tabletColumns: '2',
      mobileColumns: '1',
      showButtons: true,
      hoverStyle: 'lift',
      cardBackground: '#ffffff',
      items: [
        {
          title: 'Tính năng thứ nhất',
          description: 'Mô tả tính năng.',
          icon: 'bolt',
          imageUrl: '',
          buttonText: 'Xem thêm',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
        {
          title: 'Tính năng thứ hai',
          description: 'Mô tả tính năng.',
          icon: 'check',
          imageUrl: '',
          buttonText: 'Xem thêm',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
        {
          title: 'Tính năng thứ ba',
          description: 'Mô tả tính năng.',
          icon: 'star',
          imageUrl: '',
          buttonText: 'Xem thêm',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
      ],
    },
    fields: [
      { name: 'desktopColumns', label: 'Số cột desktop', control: 'number' },
      { name: 'tabletColumns', label: 'Số cột tablet', control: 'number' },
      { name: 'mobileColumns', label: 'Số cột mobile', control: 'number' },
      { name: 'showButtons', label: 'Hiển thị button', control: 'checkbox' },
      {
        name: 'hoverStyle', label: 'Hiệu ứng hover', control: 'select', options: [
          { label: 'Nâng thẻ', value: 'lift' }, { label: 'Đổi viền', value: 'border' },
          { label: 'Không hiệu ứng', value: 'none' },
        ],
      },
      { name: 'cardBackground', label: 'Màu nền thẻ', control: 'color' },
      {
        name: 'items',
        label: 'Danh sách tính năng',
        control: 'repeater',
        itemFields: [
          { name: 'title', label: 'Tiêu đề', control: 'text' },
          { name: 'description', label: 'Mô tả', control: 'textarea' },
          {
            name: 'icon',
            label: 'Icon',
            control: 'select',
            options: [
              { label: 'Tia chớp', value: 'bolt' },
              { label: 'Dấu tích', value: 'check' },
              { label: 'Ngôi sao', value: 'star' },
              { label: 'Trái tim', value: 'heart' },
              { label: 'Không dùng icon', value: 'none' },
            ],
          },
          {
            name: 'imageUrl',
            label: 'Hình ảnh',
            control: 'image',
            uploadFolder: 'landing/features',
          },
          { name: 'buttonText', label: 'Nhãn nút', control: 'text' },
          { name: 'buttonUrl', label: 'URL của nút', control: 'text' },
          { name: 'buttonOpenInNewTab', label: 'Mở nút trong tab mới', control: 'checkbox' },
        ],
        itemDefaults: {
          title: 'Tính năng mới',
          description: 'Mô tả tính năng.',
          icon: 'bolt',
          imageUrl: '',
          buttonText: 'Xem thêm',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
      },
    ],
  },
  {
    type: 'pricing',
    label: 'Bảng giá',
    icon: '₫',
    defaults: {
      title: 'Bảng giá',
      description: 'Chọn gói phù hợp với bạn.',
      borderRadius: '16px',
      background: '#0e0e10',
      textColor: '#ffffff',
      columns: '3',
      currency: '₫',
      billingCycle: '/tháng',
      plans: [
        {
          name: 'Cơ bản',
          price: '0₫',
          description: 'Dành cho cá nhân',
          benefits: [{ text: 'Quyền lợi cơ bản' }],
          icon: 'check',
          imageUrl: '',
          featured: false,
          background: '',
          textColor: '',
          borderColor: '',
          mutedColor: '',
          accentColor: '',
          buttonBackground: '',
          buttonTextColor: '',
          buttonText: 'Chọn gói',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
        {
          name: 'Nâng cao',
          price: 'Liên hệ',
          description: 'Dành cho doanh nghiệp',
          benefits: [{ text: 'Đầy đủ tính năng' }],
          icon: 'star',
          imageUrl: '',
          featured: true,
          background: '',
          textColor: '',
          borderColor: '',
          mutedColor: '',
          accentColor: '',
          buttonBackground: '',
          buttonTextColor: '',
          buttonText: 'Chọn gói',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
      ],
    },
    fields: [
      { name: 'title', label: 'Tiêu đề', control: 'text' },
      { name: 'description', label: 'Mô tả', control: 'textarea' },
      { name: 'borderRadius', label: 'Bo góc', control: 'text' },
      { name: 'background', label: 'Màu nền khu vực', control: 'color' },
      { name: 'textColor', label: 'Màu chữ khu vực', control: 'color' },
      { name: 'columns', label: 'Số cột desktop', control: 'number' },
      { name: 'currency', label: 'Đơn vị tiền tệ', control: 'text' },
      { name: 'billingCycle', label: 'Chu kỳ giá', control: 'text' },
      {
        name: 'plans',
        label: 'Các gói',
        control: 'repeater',
        itemFields: [
          { name: 'name', label: 'Tên gói', control: 'text' },
          { name: 'price', label: 'Giá', control: 'text' },
          { name: 'description', label: 'Mô tả', control: 'text' },
          {
            name: 'benefits', label: 'Danh sách quyền lợi', control: 'repeater',
            itemFields: [{ name: 'text', label: 'Quyền lợi', control: 'text' }],
            itemDefaults: { text: 'Quyền lợi mới' },
          },
          {
            name: 'icon',
            label: 'Icon',
            control: 'select',
            options: [
              { label: 'Dấu tích', value: 'check' },
              { label: 'Ngôi sao', value: 'star' },
              { label: 'Tia chớp', value: 'bolt' },
              { label: 'Không dùng icon', value: 'none' },
            ],
          },
          {
            name: 'imageUrl',
            label: 'Hình ảnh',
            control: 'image',
            uploadFolder: 'landing/pricing',
          },
          { name: 'featured', label: 'Gói nổi bật', control: 'checkbox' },
          { name: 'background', label: 'Màu nền gói', control: 'colorOptional' },
          { name: 'textColor', label: 'Màu chữ gói', control: 'colorOptional' },
          { name: 'borderColor', label: 'Màu viền gói', control: 'colorOptional' },
          { name: 'mutedColor', label: 'Màu chữ phụ (mô tả)', control: 'colorOptional' },
          { name: 'accentColor', label: 'Màu nhấn (badge/icon)', control: 'colorOptional' },
          { name: 'buttonBackground', label: 'Màu nền nút', control: 'colorOptional' },
          { name: 'buttonTextColor', label: 'Màu chữ nút', control: 'colorOptional' },
          { name: 'buttonText', label: 'Nhãn nút', control: 'text' },
          { name: 'buttonUrl', label: 'URL của nút', control: 'text' },
          { name: 'buttonOpenInNewTab', label: 'Mở nút trong tab mới', control: 'checkbox' },
        ],
        itemDefaults: {
          name: 'Gói mới',
          price: 'Liên hệ',
          description: 'Mô tả gói',
          benefits: [{ text: 'Quyền lợi mới' }],
          icon: 'check',
          imageUrl: '',
          featured: false,
          background: '',
          textColor: '',
          borderColor: '',
          mutedColor: '',
          accentColor: '',
          buttonBackground: '',
          buttonTextColor: '',
          buttonText: 'Chọn gói',
          buttonUrl: '#',
          buttonOpenInNewTab: false,
        },
      },
    ],
  },
  {
    type: 'divider',
    label: 'Đường phân cách',
    icon: '—',
    defaults: {
      color: '#e8e8ee',
      width: '100',
      spaceTop: '22',
      spaceBottom: '22',
      spaceLeft: '32',
      spaceRight: '32',
      mobileSpaceTop: '16',
      mobileSpaceBottom: '16',
      mobileSpaceLeft: '16',
      mobileSpaceRight: '16',
    },
    fields: [
      { name: 'color', label: 'Màu đường kẻ', control: 'color' },
      { name: 'width', label: 'Độ rộng (%)', control: 'number' },
      { name: 'spaceTop', label: 'Khoảng cách phía trên desktop (px)', control: 'number' },
      { name: 'spaceBottom', label: 'Khoảng cách phía dưới desktop (px)', control: 'number' },
      { name: 'spaceLeft', label: 'Khoảng cách bên trái desktop (px)', control: 'number' },
      { name: 'spaceRight', label: 'Khoảng cách bên phải desktop (px)', control: 'number' },
      { name: 'mobileSpaceTop', label: 'Khoảng cách phía trên mobile (px)', control: 'number' },
      { name: 'mobileSpaceBottom', label: 'Khoảng cách phía dưới mobile (px)', control: 'number' },
      { name: 'mobileSpaceLeft', label: 'Khoảng cách bên trái mobile (px)', control: 'number' },
      { name: 'mobileSpaceRight', label: 'Khoảng cách bên phải mobile (px)', control: 'number' },
    ],
  },
  {
    type: 'spacer',
    label: 'Khoảng trống',
    icon: '↕',
    defaults: { height: '48' },
    fields: [
      { name: 'height', label: 'Chiều cao (px)', control: 'number' },
    ],
  },
  {
    type: 'footer',
    label: 'Chân trang',
    icon: '▂',
    defaults: {
      logoUrl: '', brandName: 'Tên doanh nghiệp', description: '',
      background: '#111827', textColor: '#ffffff',
      columns: [{ title: 'Liên kết', links: [{ label: 'Trang chủ', url: '/', openInNewTab: false }] }],
      socialLinks: [{ label: 'Facebook', url: '#', openInNewTab: true }],
      businessInfo: 'Địa chỉ · Điện thoại · Email',
      text: '© 2026 Tên doanh nghiệp',
    },
    fields: [
      { name: 'logoUrl', label: 'Logo', control: 'image', uploadFolder: 'landing/footer' },
      { name: 'brandName', label: 'Tên thương hiệu', control: 'text' },
      { name: 'description', label: 'Mô tả ngắn', control: 'textarea' },
      { name: 'background', label: 'Màu nền', control: 'color' },
      { name: 'textColor', label: 'Màu chữ', control: 'color' },
      {
        name: 'columns', label: 'Các cột liên kết', control: 'repeater',
        itemFields: [
          { name: 'title', label: 'Tiêu đề cột', control: 'text' },
          {
            name: 'links', label: 'Liên kết', control: 'repeater',
            itemFields: [
              { name: 'label', label: 'Nhãn', control: 'text' },
              { name: 'url', label: 'URL', control: 'text' },
              { name: 'openInNewTab', label: 'Mở tab mới', control: 'checkbox' },
            ],
            itemDefaults: { label: 'Liên kết mới', url: '#', openInNewTab: false },
          },
        ],
        itemDefaults: { title: 'Cột mới', links: [] },
      },
      {
        name: 'socialLinks', label: 'Mạng xã hội', control: 'repeater',
        itemFields: [
          { name: 'label', label: 'Tên', control: 'text' },
          { name: 'url', label: 'URL', control: 'text' },
          { name: 'openInNewTab', label: 'Mở tab mới', control: 'checkbox' },
        ],
        itemDefaults: { label: 'Mạng xã hội', url: '#', openInNewTab: true },
      },
      { name: 'businessInfo', label: 'Thông tin doanh nghiệp', control: 'textarea' },
      { name: 'text', label: 'Bản quyền', control: 'textarea' },
    ],
  },
  ...EXTENDED_LANDING_BLOCKS,
  {
    type: CUSTOM_JSX_TYPE,
    label: 'Custom JSX',
    icon: '</>',
    custom: true,
    defaults: {
      name: 'Custom JSX block',
      title: 'Custom JSX block',
      source: CUSTOM_JSX_TEMPLATE,
    },
    fields: [
      { name: 'name', label: 'Tên block', control: 'text' },
      { name: 'title', label: 'Tiêu đề truyền vào props', control: 'text' },
      { name: 'routePath', label: 'Route hiển thị (ví dụ /category/:category)', control: 'text' },
    ],
  },
]

export const getLandingBlock = (type) => (
  LANDING_BLOCKS.find(block => block.type === type) ?? null
)

export const createLandingBlock = (type) => {
  const definition = getLandingBlock(type)
  if (!definition) return null

  return {
    id: createId(type),
    type,
    props: {
      blockTitle: '',
      ...COMMON_BLOCK_DEFAULTS,
      ...JSON.parse(JSON.stringify(definition.defaults)),
    },
  }
}
